### PR TITLE
Fix #17 Add a way to disable the SSL verification in download_utils

### LINKED ISSUE #17: Add a way to disable the SSL verification in download_utils
if the SSL certificate cannot be validate, an error is thrown when downloading a file with download_utils.py:
`[Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)`

we need a way to disable SSL verification

### PR DESCRIPTION
**Pull request by segalaj**
- use requests library instead of urllib2
- add a new boolean parameter verify_ssl_certificate in the Download class

### CODE REVIEW

**Comment by lqueiroga** [comment]
Ok for this PR.
We need to do non regression test in Hammr

**Comment by DimitriSCOLE** [comment]
this fixed raise this exception : /home/developer/.usharesoft-venv/lib/python2.6/site-packages/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/home/developer/.usharesoft-venv/lib/python2.6/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning

**Comment by DimitriSCOLE** [comment]
maybe this can be solve with that https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2

**Comment by segalaj** [comment]
@DimitriSCOLE thanks for your comment, this PR is closed, could you create a new issue explaining how to reproduce the behavior you described. Thanks.

**Pull request merged**
